language: node_js
node_js:
  - "0.10"
services:
  - mongodb

before_script:
  - npm install -g gulp
  - npm install forever -g
  - npm install
  - export NODE_ENV=ci
  - gulp install
  - forever start src/server.js
  - forever list
  - sleep 5
  - forever logs 0

script:
  - gulp test

after_failure:
  - forever logs 0

after_success:
  - forever logs 0
  - echo "should deploy service to UAT env"
notifications:
  slack: ngacn:6HY5F4fqhrSPeGZi77QxTFVj
